services:
  translator_database:
    image: postgres
    volumes:
      - translator_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: translator_db
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"

  translator_app:
    image: marcinsz1993/translator_app:v4.0
    ports:
      - "8080:8080"
    depends_on:
      - translator_database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://translator_database:5432/translator_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qwerty

volumes:
  translator_postgres_data:

