spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/translator_db
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

translator:
  apiKey: DeepL-Auth-Key 5faf23e8-6f6d-4fff-ad4c-6702437406f2:fx
  uri: https://api-free.deepl.com/v2/translate
